TOKEN = 'YOUR_TOKEN'
DB_FILENAME = 'form.db'
YANDEX_DRIVE_TOKEN = 'YOYR TOKEN'
OWNER_MEMBER_ID = 0  # your tg id
YANDEX_DRIVE_DIR = 'questionnaire/'
CREDENTIALS_FILE = 'credentials.json'
GOOGLE_DRIVE_DIR_ID = 'YOUR_DRIVE_ID'
