TOKEN = 'YOUR_TOKEN'
DB_FILENAME = 'form.db'
YANDEX_DRIVE_TOKEN = 'YOUR TOKEN'
OWNER_MEMBER_ID = 597290629
CREDENTIALS_FILE = 'credentials.json'
GOOGLE_DRIVE_DIR_ID = 'YOUR_DRIVE_ID'
GOOGLE_DRIVE_TEAM_DIR_URL = 'YOUR_DRIVE_URL'
